padding = [0]
theme = "oasis_lagoon_dark"
working-dir = "C:/Users/bgarciamoura"
use-fork = false

[panel]
padding = [0]
border-width = 0.0

[window]
columns = 120
rows = 32
windows-corner-preference = "DoNotRound"
windows-use-undecorated-shadow = false
opacity = 0.8
blur = true
decorations = "enabled"

[shell]
program = "nu"
args = []

[navigation]
mode = "Tab"
hide-if-single = true
unfocused-split-opacity = 0.5

[fonts]
family = "JetBrainsMono Nerd Font"

[renderer]
performance = "High"
backend = "DX12"
filters = [
  # "C:/Users/bgarciamoura/Documents/shaders/slang-shaders/crt/crt-effects/vector-glow.slangp",
  "C:/Users/bgarciamoura/Documents/shaders/slang-shaders/dithering/jinc2-dedither.slangp",
  # "C:/Users/bgarciamoura/Documents/shaders/slang-shaders/dithering/cbod_v1.slangp",
  # "C:/Users/bgarciamoura/Documents/shaders/slang-shaders/dithering/blue_noise_dynamic_4Bit.slangp",
  # "C:/Users/bgarciamoura/Documents/shaders/slang-shaders/crt/crt-effects/vector-glow.slangp",
]
use-cpu = false

[editor]
program = "nvim"
args = []

[cursor]
shape = "block"
blinking = true
blinking-interval = 800

[title]
content = "{{ TITLE || RELATIVE_PATH || PROGRAM }}"

[bindings]
keys = [
  { key = "t", with = "control | shift", action = "CreateTab" },
  { key = "w", with = "control | shift", action = "CloseTab" },
  { key = "tab", with = "control", action = "SelectNextTab" },
  { key = "tab", with = "control | shift", action = "SelectPrevTab" },
]
