[colors]
background = "#171345"
foreground = "#EEEAFE"

cursor = "#F0E68C"
vi-cursor = "#F8B471"

selection-background = "#433F38"
selection-foreground = "#EEEAFE"

black   = "#171345"
red     = "#FF7979"
green   = "#7FCF78"
yellow  = "#F0E68C"
blue    = "#81C0FF"
magenta = "#C695FF"
cyan    = "#68C0B6"
white   = "#FFF7D7"

light-black   = "#8A82B3"
light-red     = "#FFA0A0"
light-green   = "#A3E39A"
light-yellow  = "#F8B471"
light-blue    = "#87CEEB"
light-magenta = "#D2ADFF"
light-cyan    = "#8FD1C7"
light-white   = "#F7F4E9"

tabs        = "#8A82B3"
tabs-active = "#EEEAFE"
bar         = "#171345"
