[colors]
background = "#18231A"
foreground = "#DDF0E5"

cursor = "#F0E68C"
vi-cursor = "#F8B471"

selection-background = "#334137"
selection-foreground = "#DDF0E5"

black   = "#18231A"
red     = "#FF7979"
green   = "#7FCF78"
yellow  = "#F0E68C"
blue    = "#81C0FF"
magenta = "#C695FF"
cyan    = "#68C0B6"
white   = "#FFF7D7"

light-black   = "#5B7360"
light-red     = "#FFA0A0"
light-green   = "#A3E39A"
light-yellow  = "#F8B471"
light-blue    = "#87CEEB"
light-magenta = "#D2ADFF"
light-cyan    = "#8FD1C7"
light-white   = "#F7F4E9"

tabs        = "#5B7360"
tabs-active = "#DDF0E5"
bar         = "#18231A"
