[colors]
background = "#2A1412"
foreground = "#FFE0DA"

cursor = "#F0E68C"
vi-cursor = "#F8B471"

selection-background = "#462A25"
selection-foreground = "#FFE0DA"

black   = "#2A1412"
red     = "#FF7979"
green   = "#7FCF78"
yellow  = "#F0E68C"
blue    = "#81C0FF"
magenta = "#C695FF"
cyan    = "#68C0B6"
white   = "#FFF7D7"

light-black   = "#83615B"
light-red     = "#FFA0A0"
light-green   = "#A3E39A"
light-yellow  = "#F8B471"
light-blue    = "#87CEEB"
light-magenta = "#D2ADFF"
light-cyan    = "#8FD1C7"
light-white   = "#F7F4E9"

tabs        = "#83615B"
tabs-active = "#FFE0DA"
bar         = "#2A1412"
